name: geny_test_app
description: Geny Test App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  provider: ^6.1.5+1

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/business_data.json
